# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

python:
  - 2.7

install:
  - pip install codecov

script:
  - coverage run test.py

after_success:
  - codecov
