version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install dominance-analysis
        
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install dominance-analysis
        
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
