version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: 
      command:
        pip install codecov
        pip install dominance-analysis
        pip install nose coverage
        pip install coveralls
  test:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
      command:
        pip install codecov
        pip install dominance-analysis
        pip install nose coverage
        pip install coveralls
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
