language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install codecov
  - pip install dominance-analysis
  - pip install nose coverage
  - pip install coveralls


script:
  - coverage run test.py
  
after_success:
  - coveralls
  - codecov
